---
- name: Prepare nodes
  hosts: k8s_cluster
  become: true
  tasks:
    - name: Update cache and upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Install admin and network tools
      ansible.builtin.dnf:
        name:
          - nano
          - vim-enhanced
          - git
          - curl
          - wget
          - bash-completion
          - tar
          - tmux
          - iproute
          - net-tools
          - bind-utils
          - traceroute
          - tcpdump
          - lsof
          - sysstat
          - dnf-utils
          - python3
          - python3-pip
          - chrony
        state: present

    - name: Enable and start chronyd and sshd
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - chronyd
        - sshd

    - name: Show system summary
      ansible.builtin.debug:
        msg: "Host={{ ansible_hostname }} | OS={{ ansible_distribution }} {{ ansible_distribution_version }} | Kernel={{ ansible_kernel }} | vCPU={{ ansible_processor_vcpus }} | RAM={{ ansible_memtotal_mb }} MB"

    - name: Check if reboot is needed
      ansible.builtin.command: needs-restarting -r
      register: reboot_check
      failed_when: reboot_check.rc not in [0, 1]
      changed_when: false

    - name: Reboot workers only if needed
      ansible.builtin.reboot:
      when:
        - reboot_check.rc == 1
        - "'k8s_workers' in group_names"

    - name: Warn if controller needs a manual reboot
      ansible.builtin.debug:
        msg: "cp1 needs a reboot; do it manually later (never automatically)."
      when:
        - reboot_check.rc == 1
        - "'k8s_master' in group_names"
